name: Android Lint

on:
  pull_request:

jobs:
  android_lint:
    name: Run Android Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.3.0

      - name: Cache Gradle Files
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Android Lint
        run: ./gradlew scratchoff:lintDebug

      - name: Review Lint Results
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat scratchoff/build/reports/lint-results-debug.sarif \
            | reviewdog \
              -name=android-lint \
              -f=sarif \
              -reporter=github-pr-review \
              -level=warning