name: Detect Secrets

on:
  pull_request:

jobs:
  secrets_detection:
    name: Run detect-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: reviewdog/action-detect-secrets@v0.17.0
        with:
          fail_on_error: true
          filter_mode: diff_context
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
