name: GitHub Actions Lint

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  github_actions_lint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5

      - uses: reviewdog/action-actionlint@v1.46.0
        with:
          fail_on_error: true
          filter_mode: diff_context
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
