name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  unit_test:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-test.yml

  publish_to_maven_central:
    name: Publish to Maven Central Repository
    needs:
      - unit_test
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: actions/setup-java@v5.2.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Publish to Maven Central Staging Repository
        env:
          LIBRARY_RELEASE_MODE: true
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          RELEASE_SIGNING_KEY_ID: ${{ secrets.RELEASE_SIGNING_KEY_ID }}
          RELEASE_SIGNING_KEY: ${{ secrets.RELEASE_SIGNING_KEY }}
          RELEASE_SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}
        run: ./gradlew scratchoff:publishReleasePublicationToMavenCentralRepository

      - name: Transfer Deployment to Central Publisher Portal
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        run: |
          curl -X POST \
            -u "${MAVEN_CENTRAL_USERNAME}:${MAVEN_CENTRAL_TOKEN}" \
            https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/com.jackpocket

  create_release_for_tag:
    name: Create Github Release
    needs:
      - publish_to_maven_central
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Generate Changelog for Release Body
        id: generate_changelog
        uses: mikepenz/release-changelog-builder-action@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/changelog_config.json"

      - name: Create Release For Tag
        uses: ncipollo/release-action@v1.21.0
        with:
          body: ${{ steps.generate_changelog.outputs.changelog }}
