name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  unit_test:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-test.yml

  publish_to_maven_central:
    name: Publish to Maven Central Repository
    needs:
      - unit_test
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Publish to Maven Central Staging Repository
        env:
          LIBRARY_RELEASE_MODE: true
          MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          RELEASE_SIGNING_KEY_ID: ${{ secrets.RELEASE_SIGNING_KEY_ID }}
          RELEASE_SIGNING_KEY: ${{ secrets.RELEASE_SIGNING_KEY }}
          RELEASE_SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}
        run: ./gradlew scratchoff:publishReleasePublicationToMavenCentralRepository

  create_release_for_tag:
    name: Create Github Release
    needs:
      - publish_to_maven_central
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Generate Changelog for Release Body
        id: generate_changelog
        uses: mikepenz/release-changelog-builder-action@v4.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/changelog_config.json"

      - name: Create Release For Tag
        uses: ncipollo/release-action@v1.14.0
        with:
          body: ${{ steps.generate_changelog.outputs.changelog }}
