name: Test

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache Gradle Files
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Unit Tests
        run: ./gradlew scratchoff:testDebugUnitTest