name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache Gradle Files
        uses: actions/cache@v3.3.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Unit Tests
        run: ./gradlew scratchoff:testDebugUnitTest

      - name: Evaluate Test Report
        uses: mikepenz/action-junit-report@v4.0.3
        if: always()
        with:
          report_paths: 'scratchoff/build/test-results/testDebugUnitTest/TEST-*.xml'

      - name: Generate Coverage Report
        run: ./gradlew scratchoff:koverXmlReportDebug --stacktrace

      - name: Store Coverage Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Test-Coverage
          path: scratchoff/build/reports/kover/reportDebug.xml

  report_test_coverage:
    needs: unit_test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/download-artifact@v4.1.0
        with:
          name: Test-Coverage

      - uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: reportDebug.xml
          flags: unit
          fail_ci_if_error: true
          verbose: true